DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS users_addresses;
DROP TABLE IF EXISTS addresses;
DROP TABLE IF EXISTS users;
