version: "3.9"

services:
  app:
    # image: golang:1.25.0-bookworm
    # working_dir: /app
    # volumes:
      # - ./:/app
    command: sh -c "go run ./cmd/calendar/main.go"
    environment:
      - CONFIG_PATH=/app/configs/config.docker.yaml
      - STORAGE_PASSWORD=calendarpass
      - REDIS_PASSWORD=calendarpass
      - SMTP_PASSWORD=
      - TZ=UTC
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - mailhog

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=calendar
      - POSTGRES_USER=calendar
      - POSTGRES_PASSWORD=calendarpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U calendar -d calendar"]
      interval: 5s
      timeout: 3s
      retries: 30

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "calendarpass"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a calendarpass ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 30

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

volumes:
  pgdata:
  redisdata:


