env: dev

server:
  port: 8080
  timeout: 30s
  idle_timeout: 60s

smtp:
  host: localhost
  port: 1025
  username: "email@example.com"

redis:
  host: localhost
  port: 6379
  username: default
  database: 0

storage:
  host: localhost
  port: 5432
  username: user
  database: calendar
  sslmode: disable

worker:
  interval: 1s
  limit: 100

archiver:
  interval: 30s
  older_than: 30d
  batch_size: 100
